version: '3'

services:
  broker-service:
    build:
      context: ./broker-service
    restart: always
    ports:
      - "5000:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: "80"

  logger-service:
    build:
      context: ./logger-service
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: "80"
      mongoURI: "mongodb://admin:password@mongo:27017/logs"
      RPC_PORT: "5001"
      GRPC_PORT: "50001"

  auth-service:
    build:
      context: ./auth-service
    restart: always
    ports:
      - "5001:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
      PORT: "80"

  mailer-service:
    build:
      context: ./mailer-service
    restart: always
    ports:
      - "5002:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: "80"
      MAIL_PORT: 1025
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      FROM_NAME: "Mail Hog"
      FROM_ADDRESS: "mail@test.com"

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/mongo/:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: logs

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      PORT: "80"
